files = [
'crypto.cpp',
'log.cpp',
'protocol.cpp',
'serverms.cpp',
'server.cpp',
'stream.cpp',
'tools.cpp',
'wizard.cpp',
]
lpath = ['../enet/.libs']
libs = ['enet','z','pthread','util','dl','m']
lflags = '-Xlinker'
flags = '-DSTANDALONE -I. -Ibot -I../enet/include -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes'

acserver = Program('ac_server',files, CCFLAGS=flags,LIBS=libs,LIBPATH=lpath,LINKFLAGS=lflags)
Alias('install',InstallAs('../../bin/native_server', acserver))

